### ISSUE TITLE
请问可以发个Release的apk包尝鲜嘛？

### ISSUE THREAD

**Issue by SeanLi-OI** [hjthjthjt/Rn6Pan#1]
6pan官方客户端没有预览功能，想尝试下这个。

**Comment by TigerBeanst** [comment]
其实官方有预览功能，不过他们的预览功能是用的专门弄的预览API，那个API有时候会滤掉一些视频，以及如果 MIME 不是 video/* 的话视频是没法预览的（图片同理）。所以我用的下载API做预览。

暂且先打了个包，比较明显的问题可以看看 release 详情。

edit：我傻了，原来是我订阅过期了23333下载还是没问题的
https://github.com/hjthjthjt/Rn6Pan/releases/tag/alpha_v0.1.0.1
