### ISSUE TITLE
图标是如何获得的？能否分享一下

### ISSUE THREAD

**Issue by zerorooot** [hjthjthjt/Rn6Pan#3]
比如https://github.com/hjthjthjt/Rn6Pan/blob/master/app/src/main/res/drawable/file_icon_pic.xml这个图标，是从那个网站下载的呢？可否分享一下。感谢感谢

**Comment by TigerBeanst** [comment]
文件图标是从阿里巴巴的 iconfont 拿的：https://www.iconfont.cn/collections/detail?cid=21246

除了文件类型 apk 的图标，因为没有对应的图标我就拿 PS 自己改了一份

**Comment by zerorooot** [comment]
多谢
